services:
  weiver-db:
    image: postgres:15-alpine
    container_name: weiver-postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${LOCAL_DB_USER}
      POSTGRES_PASSWORD: ${LOCAL_DB_PASSWORD}
      POSTGRES_DB: weiver_db
    volumes:
      - weiver-postgres-data:/var/lib/postgresql/data
    networks:
      - weiver-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${LOCAL_DB_USER} -d weiver_db"]
      interval: 10s
      retries: 5
      start_period: 30s

  weiver-redis:
    image: redis:7-alpine
    container_name: weiver-redis
    ports:
      - "6379:6379"
    networks:
      - weiver-net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 5

  weiver-rabbitmq:
    image: rabbitmq:4.2.6-management
    container_name: weiver-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - weiver-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - weiver-net
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      retries: 5
      start_period: 20s

volumes:
  weiver-postgres-data:
  weiver-rabbitmq-data:




networks:
  weiver-net:
    name: weiver-net
    driver: bridge