spring:
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

server:
  port: 8080

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html